### ISSUE TITLE
On Up key press focus goes to header (Menu Navigation) titles but header (Menu Navigation) is in collapsed mode.

### ISSUE THREAD

**Issue by ImSaumilShah** [Arpit0492/TVNavigationMenu#1]

**Comment by Arpit0492** [comment]
@ImSaumilShah on Up keypress from where? If I understand it right, you are pressing DPAD_UP from rows and focus shifts to side menu even though side menu is in collapsed mode. So, for that just need to restrict the DPAD_UP event from the top row and `row.requestfocus()` for the row itself.
